version: '3'
services:
  auth:
    image: auth:1.0
    ports:
      - "8181:8181"
    environment:
      - AUTH_PORT=8181
      #these 2 values should be added to a secret instead but will leave them here for now.
      - AUTH_BANK_SECRET_KEY=YmFuay1zZWNyZXQta2V5LWF1dGhlbnRpY2F0aW9u
      - AUTH_PAYMENT_PLATFORM_SECRET_KEY=cGF5bWVudC1wbGF0Zm9ybS1zZWNyZXQtYXV0aGVudGljYXRpb24=
  bank:
    image: bank:1.0
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - AUTH_PATH=http://host.docker.internal:8181/auth/token
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/
      - MONGODB_DATABASE=bank
      - MONGODB_CARD_COLLECTION=card
      - MONGODB_CUSTOMER_COLLECTION=customer
      - MONGODB_TRANSACTION_COLLECTION=transaction
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
    networks:
      - bank-networks
    depends_on:
      - mongodb
      - auth    
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - bank-networks
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - bank-networks
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

networks:
  bank-networks:
    driver: bridge
